Calife sprint6
RafaelNCST/compassflix pull request #35
Opened 2022-09-07 15:25 UTC by LuizaCalife

Created List Screen button and modal

2022-09-07 15:43 UTC, RafaelNCST commented on __tests__/UserTests/Containers.js
> +import React from 'react';
Esse arquivo serve para que? Não está testando nada aqui, tudo que tem nele já tem testado em outro arquivo.

2022-09-07 15:44 UTC, RafaelNCST commented on src/routes/listButton.js
> +import React from 'react';
Mude o nome do arquivo pra seguir o padrão dos outros stacks. listButton.js não é um bom nome.

2022-09-07 15:47 UTC, RafaelNCST commented on src/screens/ListScreen/components/ButtonAdd/index.js
> +import React, { useState } from 'react';
Manda esse visible e setVisible para o index.js da screen e muda o nome deles para visibleAdd e setVisibleAdd e depois tu passa eles dois por props pra essa parte do ButtonAdd.

2022-09-07 15:48 UTC, RafaelNCST requested changes
Arrume as mudanças pedidas.

2022-09-08 00:42 UTC, RafaelNCST approved these changes

2022-09-08 00:50 UTC, CollyerXTS approved these changes

2022-09-08 00:52 UTC, merged